### ISSUE TITLE
Major - passwords visible in h2db.mv.db file

### ISSUE THREAD

**Issue by JohnDBallentineIII** [informix/informixhq-server#10]
If you do a 'strings' or similar program on the database file, the user names and passwords used to connect to the Informix servers are visible as plain text, no encryption.

(snipped)
chunk:1e,block:6,len:1,map:23,max:1120,next:9,pages:8,root:78000006e09,time:4145c1,version:1e

1XTest database serverV(hostname)
GK(my user)K(password)
sensors
alerts
disabled
2ZReport ServerS(hostname)
GK(my user)K(password)K(my other user)K(password)0w
sensors
alerts
(snipped)

**Comment by JohnDBallentineIII** [comment]
Duplicate of 'Support for encryting H2 database', closing

**Comment by ekuehnhausen** [comment]
Please ignore that commit that was added to this issue. I used the wrong issue number.
