### ISSUE TITLE
Support for encrypting H2 database

### ISSUE THREAD

**Issue by lfsm** [informix/informixhq-server#2]
In the embedded H2 database, the passwords for the monitor user and admin user of each configured Informix server are stored in plain text.  
If it is a necessity for those passwords to be in plain text, there should at least be a section in the documentation about securing the H2 database file (or maybe have InformixHQ server check for that).

**Comment by ekuehnhausen** [comment]
We'll add support in InformixHQ to encrypt the H2 database in an upcoming release.

In the meantime, if you are concerned with security of the H2 database file, you should restrict permissions on that file. The user who runs the InformixHQ server needs read/write access to the file, but you can restrict access to that h2 file from all other users.

**Comment by ekuehnhausen** [comment]
Fixed in version 0.2.0.
