### ISSUE TITLE
Minimal privileges required for monitor user

### ISSUE THREAD

**Issue by lfsm** [informix/informixhq-server#3]
This is a request for the server documentation:
What are the privileges required by the monitor user for an Informix Instance?

I have setup a VM to test InformixHQ, but I am using the "informix" user for everything.
For the monitor I would like to use a less privileged user.

**Comment by ekuehnhausen** [comment]
The InformixHQ documentation was updated today and this information can now be found here https://informix.github.io/informixhq-server/faq.html#credentials-vs-permissions

_The monitoring credentials are used by the InformixHQ server whenever a user navigates to any part of the UI that issues a REST query which just needs to gather data from the live Informix database server instance. The user provided for the monitoring credentials needs read access to the sysmaster database. The admin credentials are used whenever a user in the UI requests that an administration action be performed on the database server, for example create a dbspace or edit an onconfig parameter. The user provided for the admin credentials should be a DBSA and will need access to the sysadmin database and permissions to run SQL Admin API commands on the database server._
